name: microstack
base: core22
summary: Dead simple OpenStack installation
license: Apache-2.0
description: |
  Microstack aims to provide a scalable, simple to deploy OpenStack solution.
version: yoga

confinement: strict
grade: devel

architectures:
  - build-on: amd64

layout:
  /usr/share/terraform/plugins:
    symlink: $SNAP_DATA/terraform-plugins

apps:
  microstack:
    command: bin/microstack
    plugs:
      - dot-local-share-juju
      - dot-kube
      - home
      - network
      - network-bind
      - ssh-public-keys
    environment:
      PATH: $PATH:$SNAP/juju/bin

  terraform:
    command: bin/terraform
    plugs:
      - home
      - network
      - ssh-public-keys
      - juju-client-observe
    environment:
      PATH: $PATH:$SNAP/juju/bin

parts:
  microstack:
    plugin: python
    source: .
    build-packages:
      - git
    python-requirements:
      - requirements.txt
    override-build: |
      craftctl default
      snap-helpers write-hooks

  terraform:
    plugin: go
    source: https://github.com/hashicorp/terraform
    source-depth: 1
    source-type: git
    source-tag: "v1.3.7"
    build-snaps: [go]
    build-environment:
      - CGO_ENABLED: "0"
      - GOFLAGS: "-mod=readonly"
    override-build: |
      go mod download
      go build -ldflags "-s -w"
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp terraform $SNAPCRAFT_PART_INSTALL/bin/terraform
    stage:
      - bin/terraform

  configure:
    plugin: dump
    after: [terraform]
    source: configure/
    override-build: |
      craftctl default
      cd $SNAPCRAFT_PART_INSTALL/etc/configure
      $SNAPCRAFT_STAGE/bin/terraform providers mirror $SNAPCRAFT_STAGE/terraform-providers

  deploy:
    plugin: dump
    after: [terraform]
    source: https://github.com/openstack-snaps/sunbeam-terraform
    source-depth: 1
    source-type: git
    organize:
      '*': etc/deploy/
    override-build: |
      craftctl default
      cd $SNAPCRAFT_PART_INSTALL
      $SNAPCRAFT_STAGE/bin/terraform init
      $SNAPCRAFT_STAGE/bin/terraform providers mirror $SNAPCRAFT_STAGE/terraform-providers
      rm -rf $SNAPCRAFT_PART_INSTALL/.terraform

plugs:
  # Needed for juju client to autodiscover microk8s cloud
  microk8s:
    interface: content
    content: microk8s
    target: $SNAP_DATA/microk8s

  juju-bin:
    interface: content
    content: juju
    target: $SNAP/juju

  hypervisor-config:
    interface: content
    content: openstack-hypervisor
    target: $SNAP_DATA

  dot-local-share-juju:
    interface: personal-files
    write:
      - $HOME/.local/share/juju

  dot-kube:
    interface: personal-files
    read:
      - $HOME/.kube
